# Generated by Django 5.1.5 on 2025-02-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.ImageField(default='https://placehold.co/5000x5000', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
